version: '3'

services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_database
      TZ: "Asia/Tokyo"
    ports:
      - 5433:5432
    volumes:
      - ./db/sql:/docker-entrypoint-initdb.d
